# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
        migrations.AddField(
            model_name='blog',
            name='tagline',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
